### ISSUE TITLE
请教一下，80x86typecho镜像修改NG配置

### ISSUE THREAD

**Issue by gaoxianglyx** [ttys3/nanodm.net#1]
我在docker上跑起来了你的80x86镜像，现在想修改ng，来实现访问文件夹下的静态html的路由，请问一下ng可以在哪里修改了？

**Comment by ttys3** [comment]
/etc/nginx/conf.d/
you can check youself, no need to ask anybody

**Comment by gaoxianglyx** [comment]
多谢，我尝试修改了overlay2下的这个文件，docker restart typecho后并没有生效，请问是还有其他依赖项吗？

**Comment by gaoxianglyx** [comment]
已找到，多谢。
